name: Builder Humble arm64

on:
  workflow_dispatch:
  push:
    paths:
      - ros2.repos
jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: qiayuanl/unitree_ros2
          token: ${{ secrets.GH_PAT }}
          path: 'src/unitree_ros2'
      - uses: qiayuanl/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          DEB_ARCH: arm64
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_CHECKOUT: true
          REPOS_FILE: ros2.repos
          SKIP_PACKAGES: >-
            unitree_description
